# config.make generated by configure script
POCO_CONFIG = Android
POCO_BASE = /Users/kevin/WorkSpace/DevelopSpace/poco
POCO_BUILD = /Users/kevin/WorkSpace/DevelopSpace/poco
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = 
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
